# Generated by Django 5.1.5 on 2025-02-01 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_chapter_content_chimg_alter_course_cimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chfiles',
            field=models.FileField(blank=True, null=True, upload_to='chfiles/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chimg',
            field=models.ImageField(blank=True, null=True, upload_to='chaptersimg/'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='cms.course'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='disp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters_created', to='cms.teacher'),
        ),
        migrations.AlterField(
            model_name='chapter_content',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='cms.chapter'),
        ),
        migrations.AlterField(
            model_name='chapter_content',
            name='chfiles',
            field=models.FileField(blank=True, null=True, upload_to='chfiles/'),
        ),
        migrations.AlterField(
            model_name='chapter_content',
            name='chimg',
            field=models.ImageField(blank=True, null=True, upload_to='chaptersimg/'),
        ),
        migrations.AlterField(
            model_name='chapter_content',
            name='dispcription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cimg',
            field=models.FileField(blank=True, null=True, upload_to='coursevideos/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='disp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='cms.teacher'),
        ),
    ]
