# Generated by Django 5.1.5 on 2025-02-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_predefined',
            field=models.BooleanField(default=False),
        ),
    ]
